// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKM6c2dVnp2gfnOC9e-Q9mZ1WMQxfrw4s',
    appId: '1:246516688633:android:83f92c4b486d016e9de428',
    messagingSenderId: '246516688633',
    projectId: 'iot-nhom08',
    databaseURL: 'https://iot-nhom08-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-nhom08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCex45m7XA3neu7c1ILd_JZsteS4AbDg5w',
    appId: '1:246516688633:ios:e0a8638a510865109de428',
    messagingSenderId: '246516688633',
    projectId: 'iot-nhom08',
    databaseURL: 'https://iot-nhom08-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-nhom08.firebasestorage.app',
    iosBundleId: 'com.example.denhoc',
  );

}